apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-cu-cp-configmap
  namespace: oai5g-split
data:
  cucp.conf: |
    Active_gNBs = ( "oai-cu-cp");
    # Asn1_verbosity, choice in: none, info, annoying
    Asn1_verbosity = "none";
    Num_Threads_PUSCH = 8;
    sa = 1;

    gNBs =
    (
     {
        ////////// Identification parameters:
        gNB_ID = 0xe00;

        gNB_name  = "oai-cu-cp";

        // Tracking area code, 0x0000 and 0xfffe are reserved values
        tracking_area_code  = 1;
        plmn_list = ({ mcc = 001; mnc = 01; mnc_length = 2; snssaiList = ({ sst = 1 }) });

        nr_cellid = 12345678L;

        tr_s_preference = "f1";

        // F1-C (CU-CP side)
        local_s_if_name = "eth0";
        local_s_address = "oai-cu-cp";
        remote_s_address = "oai-du";
        local_s_portc   = 501;
        local_s_portd   = 2153;
        remote_s_portc  = 500;
        remote_s_portd  = 2153;

        # ------- SCTP definitions
        SCTP :
        {
            # Number of streams to use in input/output
            SCTP_INSTREAMS  = 2;
            SCTP_OUTSTREAMS = 2;
        };

        ////////// AMF parameters:
        amf_ip_address      = ( { ipv4 = "oai-amf";});

        // E1 interface CU-CP <-> CU-UP
        E1_INTERFACE =
        (
          {
            type = "cp";
            ipv4_cucp = "oai-cu-cp";
            port_cucp = 38462;
            ipv4_cuup = "oai-cu-up";
            port_cuup = 38462;
          }
        );

        NETWORK_INTERFACES :
        {
          # From the CU-CP point of view, this is the IP where AMF reaches NGAP
          GNB_IPV4_ADDRESS_FOR_NG_AMF = "oai-cu-cp";
        };
      }
    );

    security = {
      ciphering_algorithms = ( "nea0" );
      integrity_algorithms = ( "nia2", "nia0" );
      drb_ciphering = "yes";
      drb_integrity = "no";
    };

    log_config :
    {
      global_log_level   = "info";
      hw_log_level       = "info";
      phy_log_level      = "info";
      mac_log_level      = "info";
      rlc_log_level      = "debug";
      pdcp_log_level     = "info";
      rrc_log_level      = "info";
      f1ap_log_level     = "info";
      ngap_log_level     = "debug";
    };
