apiVersion: v1
kind: Service
metadata:
  name: oai-cu
  namespace: oai5g-split
spec:
  selector:
    app: oai-cu-cp
  ports:
    - name: f1c
      port: 38472
      targetPort: 38472
      protocol: SCTP
    - name: f1u
      port: 2153
      targetPort: 2153
      protocol: UDP
